xpos314/xpos314.web/Controllers/FriendController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.web.Models;

namespace xpos314.web.Controllers
{
    public class FriendController : Controller
    {
        private static List<Friend> list = new List<Friend>()
            {
                new Friend(){ Id = 1, Name = "Anwar", Address = "Ragunan" },
                new Friend(){ Id = 2, Name = "Asti", Address = "Garut"},
                new Friend(){ Id = 3, Name = "Toni", Address = "Garut"},
                new Friend(){ Id = 4, Name = "Tono", Address = "Garut2"},
                new Friend(){ Id = 5, Name = "Alwi", Address = "Riau"}
            };
        public IActionResult Index()
        {
            ViewBag.listFriend = list;

            return View(list);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Friend friend)
        {
            list.Add(friend);   
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            Friend friend = list.Find(a => a.Id == id)!;
            return View(friend);
        }
        [HttpPost]
        public IActionResult Edit(Friend data)
        {
            Friend friend = list.Find(a => a.Id == data.Id)!;
            int index = list.IndexOf(friend);

            if (index > -1)
            {
                list[index].Id = data.Id;
                list[index].Name = data.Name;
                list[index].Address = data.Address;
            }
            return RedirectToAction("Index");
        }
        public IActionResult Detail (int id)
        {
            Friend friend = list.Find(a => a.Id == id)!;
            return View(friend);
        }
        //public IActionResult Delete(int id)
        //{
        //    Friend friend = list.Find(a => a.Id == id)!;
        //    return View(friend);
        //}
        //[HttpPost]
        //public IActionResult Delete(string id)
        //{
        //    Friend data = list.Find(a => a.Id == int.Parse(id))!;
        //    list.Remove(data);
        //    return RedirectToAction("Index");
        //}

        [HttpGet]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            Friend friend = list.Find(a => a.Id == id)!;
            if (HttpContext.Request.Method == "POST")
            {
                list.Remove(friend);
                return RedirectToAction("Index");
            }
            else
            {
                return View(friend);
            }

        }
    }
}

xpos314/xpos314.web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class OrderController : Controller
    {
        private ProductService productService;
        private OrderService orderService;
        private int IdUser = 1;

        public OrderController(ProductService _productService, OrderService _orderService)
        {
            this.productService = _productService;
            this.orderService = _orderService;
        }
        public async Task<IActionResult> Catalog(VMSearchPage dataSearch)
        {
            List<VMTblProduct> dataProduct = await productService.GetAllData();

            dataSearch.MinAmount = dataSearch.MinAmount == null ? decimal.MinValue : dataSearch.MinAmount;
            dataSearch.MaxAmount = dataSearch.MaxAmount == null ? decimal.MaxValue : dataSearch.MaxAmount;
            
            if(dataSearch.NameProduct != null)
            {
                dataProduct = dataProduct.Where(a => a.NameProduct == dataSearch.NameProduct).ToList();
            }
            if (dataSearch.MinAmount != null && dataSearch.MaxAmount != null)
            {
                dataProduct = dataProduct.Where(a => a.Price >= dataSearch.MinAmount && a.Price <= dataSearch.MaxAmount).ToList();
            }
            VMOrderHeader dataHeader = HttpContext.Session.GetComplexData<VMOrderHeader>("ListCart");

            if(dataHeader == null)
            {
                dataHeader= new VMOrderHeader();
                dataHeader.ListDetails = new List<VMOrderDetail>();
            }
            var ListDetail = JsonConvert.SerializeObject(dataHeader.ListDetails);
            ViewBag.dataHeader = dataHeader;
            ViewBag.dataDetail = ListDetail;
           
            ViewBag.Search = dataSearch;
            ViewBag.CurrentPageSize = dataSearch.CurrentPageSize;

            return View(PaginationList<VMTblProduct>.CreateAsync(dataProduct, dataSearch.PageNumber ?? 1, dataSearch.pageSize ?? 3));
        }

        [HttpPost]
        public JsonResult SetSession (VMOrderHeader dataHeader)
        {
            HttpContext.Session.SetComplexData("ListCart", dataHeader);
            return Json("");
        }
        public JsonResult RemoveSession()
        {
            HttpContext.Session.Remove("ListCart");
            return Json("");
        }
        public IActionResult OrderPreview(VMOrderHeader dataHeader)
        {
            return PartialView(dataHeader);
        }
        public IActionResult SearchMenu()
        {
            return PartialView();
        }
        public async Task <JsonResult> SubmitOrder(VMOrderHeader dataHeader)
        {
            //int IdCostumer = HttpContext.Session.GetInt32("IdCostumer") ?? 0;
            dataHeader.IdCostumer = IdUser;

            VMResponse respon = await orderService.SubmitOrder(dataHeader);
            return Json(respon);
        }
        public async Task <IActionResult> HistoryOrder(VMSearchPage dataSearch)
        {
            //int IdCostumer = HttpContext.Session.GetInt32("IdCostumer") ?? 0;
            int IdCostumer = IdUser;
            List<VMOrderHeader> data = await orderService.ListHeaderDetails(IdCostumer);
            int count = await orderService.CountTransaction(IdCostumer);
            ViewBag.Count = count;

            dataSearch.MinDate = dataSearch.MinDate == null ? DateTime.MinValue : dataSearch.MinDate;
            dataSearch.MaxDate = dataSearch.MaxDate == null ? DateTime.MaxValue : dataSearch.MaxDate;

            dataSearch.MinAmount = dataSearch.MinAmount == null ? decimal.MinValue : dataSearch.MinAmount;
            dataSearch.MaxAmount = dataSearch.MaxAmount == null ? decimal.MaxValue : dataSearch.MaxAmount;

            if (!string.IsNullOrEmpty(dataSearch.CodeTransaction))
            {
                data = data.Where(a => a.CodeTransaction.ToLower()
                .Contains(dataSearch.CodeTransaction.ToLower())).ToList();
            }

            if (dataSearch.MinDate != null && dataSearch.MaxDate != null)
            {
                data = data.Where ( a => a.CreateDate >= dataSearch.MinDate && a.CreateDate <= dataSearch.MaxDate).ToList();
            }

            if (dataSearch.MinAmount != null && dataSearch.MaxAmount != null)
            {
                data = data.Where(a => a.Amount >= dataSearch.MinAmount && a.Amount <= dataSearch.MaxAmount).ToList();
            }

            ViewBag.search = dataSearch;

            return View(data);
        }
        public IActionResult Search()
        {
            return PartialView();
        }

    }
}

xpos314/xpos314.web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.viewmodels;
using xpos314.web.Services;
using xpos314.datamodels;

namespace xpos314.web.Controllers
{
    public class ProductController : Controller
    {
        
        private CategoryService categoryService;
        private VariantService variantService;
        private ProductService productService;
        private readonly IWebHostEnvironment webHostEnvironment;
        private int IdUser = 1;

        public ProductController(CategoryService _categoryService, VariantService _variantService, ProductService _productService, IWebHostEnvironment _webHostEnvironment)
        {
            
            this.categoryService = _categoryService;
            this.variantService = _variantService;
            this.productService = _productService;
            this.webHostEnvironment = _webHostEnvironment;
        }
        public async Task<IActionResult> Index(string sortOrder,
                                                string searchString,
                                                string currentFilter,
                                                int? pageNumber,
                                                int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PriceSort = sortOrder == "price" ? "price_desc" : "price";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<VMTblProduct> data = await productService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameProduct.ToLower().Contains(searchString.ToLower())
                || a.NameVariant.ToLower().Contains(searchString.ToLower())
                ).ToList();
            }
            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameProduct).ToList();
                    break;
                case "price":
                    data = data.OrderBy (a => a.Price).ToList(); 
                    break;
                case "price_desc":
                    data = data.OrderByDescending(a => a.Price).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameProduct).ToList();
                    break;
            }
            return View(PaginationList<VMTblProduct>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }
        public async Task<IActionResult> Create()
        {
            VMTblProduct data = new VMTblProduct();

            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;

			List<VMTblVariant> listVariant = await variantService.GetAllData();
			ViewBag.ListVariant = listVariant;

			return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Create([FromForm]VMTblProduct dataParam)
        {
            if(dataParam.ImageFile != null)
            {
                dataParam.Image = Upload(dataParam);
            }

            VMResponse respon = await productService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }
        public async Task <JsonResult> GetDataByIdCategory(int id)
        {
            List<VMTblVariant> data = await variantService.GetDataByIdCategory(id);
            return Json(data);
        }

        public string Upload(VMTblProduct dataParam)
        {
            string uniqueFileName = "";

            if (dataParam.ImageFile != null)
            {
                string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + dataParam.ImageFile.FileName;
                string filePath = Path.Combine(uploadFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    dataParam.ImageFile.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }
        public async Task<IActionResult> Edit(int id)
        {
            VMTblProduct data = await productService.GetDataById(id);

            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;

            List<VMTblVariant> listVariant = await variantService.GetAllData();
            ViewBag.ListVariant = listVariant;

            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Edit([FromForm]VMTblProduct dataParam)
        {
            if (dataParam.ImageFile != null)
            {
                dataParam.Image = Upload(dataParam);
            }

            VMResponse respon = await productService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }
		public async Task<IActionResult> Detail(int id)
		{
			VMTblProduct data = await productService.GetDataById(id);

			return PartialView(data);
		}
		public async Task<IActionResult> Delete(int id)
		{
			VMTblProduct data = await productService.GetDataById(id);

			return PartialView(data);
		}
		public async Task<IActionResult> SureDelete(int id)
		{

			VMResponse respon = await productService.Delete(id);

			if (respon.Success)
			{
				return RedirectToAction("Index");
			}

			return RedirectToAction("Index", id);
		}
	}
}

xpos314/xpos314.web/Controllers/VariantController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class VariantController : Controller
    {
        private CategoryService categoryService;
        private VariantService variantService;
        private int IdUser = 1;

        public VariantController(CategoryService _categoryService, VariantService _variantService)
        {

            this.categoryService = _categoryService;
            this.variantService = _variantService;

            //this.configuration = _configuration;
            //this.categoryService = new CategoryService(this.configuration);
            //this.variantService = new VariantService(this.configuration);
        }
        public async Task <IActionResult> Index(string sortOrder,
                                                string searchString,
                                                string currentFilter,
                                                int? pageNumber,
                                                int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<VMTblVariant> data = await variantService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameVariant.ToLower().Contains(searchString.ToLower())
                || a.Description.ToLower().Contains(searchString.ToLower())
                ).ToList();
            }
            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameVariant).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameVariant).ToList();
                    break;
            }
            return View(PaginationList<VMTblVariant>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }
        public async Task <IActionResult> Create()
        {
            VMTblVariant data = new VMTblVariant();
            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;

            return PartialView(data);
        }
        [HttpPost]
        public async Task <IActionResult> Create(VMTblVariant dataParam)
        {
            VMResponse respon = await variantService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon});
            }
           
            return View(dataParam);
        }
        public async Task <IActionResult> Edit(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);

			List<TblCategory> listCategory = await categoryService.GetAllData();
			ViewBag.ListCategory = listCategory;

            return PartialView(data);
		}
        [HttpPost]
        public async Task <IActionResult> Edit(VMTblVariant dataParam)
        {
            VMResponse respon = await variantService.Edit(dataParam);

			if (respon.Success)
			{
				return Json(new { dataRespon = respon });
			}

			return View(dataParam);
		}

		public async Task<IActionResult> Detail(int id)
		{
			VMTblVariant data = await variantService.GetDataById(id);

			List<TblCategory> listCategory = await categoryService.GetAllData();
			ViewBag.ListCategory = listCategory;

			return PartialView(data);
		}
        [HttpPost]
		public async Task<IActionResult> Detail(VMTblVariant dataParam)
		{
			VMResponse respon = await variantService.Edit(dataParam);

			if (respon.Success)
			{
				return Json(new { dataRespon = respon });
			}

			return View(dataParam);
		}
		public async Task<IActionResult> Delete(int id)
		{
			VMTblVariant data = await variantService.GetDataById(id);
			return PartialView(data);
		}
		[HttpPost]
		public async Task<IActionResult> SureDelete(int id)
		{
			
			VMResponse respon = await variantService.Delete(id);

			if (respon.Success)
			{
				return RedirectToAction("Index");
			}

			return RedirectToAction("Index", id);
		}
	}
}

xpos314/xpos314.web/Views/Shared/_Layout - Old.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - XSIS Mitra Utama</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/xpos314.web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">XSIS Mitra Utama</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Friend" asp-action="Index">Friend</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CategoryTry" asp-action="Index">Category Try</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 by alwifs - XSIS Mitra Utama - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    ...
                </div>
            </div>
        </div>
    </div>

    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

xpos314/xpos314.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - XSIS Mitra Utama</title>
    <!-- JQuery -->
    <script src="~/adminmart/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="~/adminmart/assets/images/favicon.png">
    <!-- Custom CSS -->
    <link href="~/adminmart/assets/extra-libs/c3/c3.min.css" rel="stylesheet">
    <link href="~/adminmart/assets/libs/chartist/dist/chartist.min.css" rel="stylesheet">
    <link href="~/adminmart/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/adminmart/dist/css/style.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css">

</head>
<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper" data-theme="light" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
         data-sidebar-position="fixed" data-header-position="fixed" data-boxed-layout="full">

    <partial name="_Header" />
    <partial name="_Sidebar"/>

    <div class="page-wrapper">
        
        <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 by alwifs - XSIS Mitra Utama - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    </div>

        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body" id="myModal_body">
                        ...
                    </div>
                    
                </div>
            </div>
        </div>


        <!-- Modal -->
        <div class="modal fade" id="modal_sm" tabindex="-1"
             aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-scrollable">
                <div class="modal-content">
                    <div class="modal-body" id="modal_body_sm">
                        ...
                    </div>
                </div>
            </div>
        </div>

        <!--Modal Large-->
        <div class="modal fade" id="modal_lg">
            <div class="modal-dialog modal-dialog-scrollable modal-lg">
                <div class="modal-content">
                    <div class="modal-body" id="modal_body_lg">
                        ...
                    </div>
                </div>
            </div>
        </div>

        @*spinner*@
        <div class="modal fade" id="modal_load">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body text-center" id="modal_load_body">
                        <div class="spinner-grow text-primary" role="status">
                            <span class="sr-only">Loading...</span>
                        </div>
                        <h3>Please wait..</h3>
                    </div>
                </div>
            </div>
        </div>

        <!-- All Jquery -->
        <!-- ============================================================== -->
        
        <script src="~/adminmart/assets/libs/popper.js/dist/umd/popper.min.js"></script>
        <script src="~/adminmart/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- apps -->
        <!-- apps -->
        <script src="~/adminmart/dist/js/app-style-switcher.js"></script>
        <script src="~/adminmart/dist/js/feather.min.js"></script>
        <script src="~/adminmart/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
        <script src="~/adminmart/dist/js/sidebarmenu.js"></script>
        <!--Custom JavaScript -->
        <script src="~/adminmart/dist/js/custom.min.js"></script>
        <!--This page JavaScript -->
        <script src="~/adminmart/assets/extra-libs/c3/d3.min.js"></script>
        <script src="~/adminmart/assets/extra-libs/c3/c3.min.js"></script>
        <script src="~/adminmart/assets/libs/chartist/dist/chartist.min.js"></script>
        <script src="~/adminmart/assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>
        <script src="~/adminmart/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.min.js"></script>
        <script src="~/adminmart/assets/extra-libs/jvector/jquery-jvectormap-world-mill-en.js"></script>
        <script src="~/adminmart/dist/js/pages/dashboards/dashboard1.min.js"></script>

</body>
</html>

xpos314/xpos314.web/Views/Shared/_Sidebar.cshtml
﻿<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
<aside class="left-sidebar" data-sidebarbg="skin6">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link"
                       aria-expanded="false">
                        <i data-feather="home" class="feather-icon"></i><span class="hide-menu">Dashboard</span>
                    </a>
                </li>
                <li class="list-divider"></li>
                <li class="nav-small-cap"><span class="hide-menu">Master</span></li>

                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="Friend" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="tag" class="feather-icon"></i><span class="hide-menu">
                            Friend
                        </span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="CategoryTry" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Category Try</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="VariantTry" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="calendar" class="feather-icon"></i><span class="hide-menu">Variant Try</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Category" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="tag" class="feather-icon"></i><span class="hide-menu">Category</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Variant" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="tag" class="feather-icon"></i><span class="hide-menu">Variant</span>
                    </a>
                </li>


                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Product" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="tag" class="feather-icon"></i><span class="hide-menu">Product</span>
                    </a>
                </li>

                <li class="list-divider"></li>
                <li class="nav-small-cap"><span class="hide-menu">Transaction</span></li>

                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="Order" asp-action="Catalog"
                       aria-expanded="false">
                        <i data-feather="tag" class="feather-icon"></i><span class="hide-menu">Menu Catalog</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Order" asp-action="HistoryOrder"
                       aria-expanded="false">
                        <i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">History Order</span>
                    </a>
                </li>


                <li class="list-divider"></li>


                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" href="authentication-login1.html"
                       aria-expanded="false">
                        <i data-feather="log-out" class="feather-icon"></i><span class="hide-menu">Logout</span>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>
<!-- ============================================================== -->
<!-- End Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->