xpos314/xpos314.web/Controllers/CostumerController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Service;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
	public class CostumerController : Controller
	{
		private CostumerService costumerService;
		private RoleService roleService;
		private int IdUser = 1;


		public CostumerController(RoleService _roleService, CostumerService _costumerService)
		{
			this.roleService = _roleService;
			this.costumerService = _costumerService;

			//this.configuration = _configuration;
			//this.categoryServices = new CategoryServices(this.configuration);
			//this.variantServices = new VariantServices(this.configuration);
		}
		public async Task<IActionResult> Index(string sortOrder,
											   string searchString,
											   string currentFilter,
											   int? pageNumber,
											   int? pageSize)
		{
			ViewBag.CurrentSort = sortOrder;
			ViewBag.CurrentPageSize = pageSize;
			ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

			if (searchString != null)
			{
				pageNumber = 1;

			}
			else
			{
				searchString = currentFilter;
			}

			ViewBag.CurrentFilter = searchString;

			List<VMCostumer> data = await costumerService.GetAllData();

			if (!string.IsNullOrEmpty(searchString))
			{
				data = data.Where(a => a.NameCostumer.ToLower().Contains(searchString.ToLower())
				|| a.RoleName.ToLower().Contains(searchString.ToLower())).ToList();
			}

			switch (sortOrder)
			{
				case "name_desc":
					data = data.OrderByDescending(a => a.NameCostumer).ToList();
					break;
				default:
					data = data.OrderBy(a => a.NameCostumer).ToList();
					break;
			}
			return View(PaginationList<VMCostumer>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
		}

		public async Task<IActionResult> Create()
		{
			VMCostumer data = new VMCostumer();

			List<TblRole> listRole = await roleService.GetAllData();
			ViewBag.ListRole = listRole;

			return PartialView(data);
		}

		[HttpPost]
		public async Task<IActionResult> Create(VMCostumer dataParam)
		{

			VMResponse respon = await costumerService.Create(dataParam);

			if (respon.Success)
			{
				return Json(new { dataRespon = respon });

			}
			return View(dataParam);
		}

		public async Task<IActionResult> Edit(int id)
		{
			VMCostumer data = await costumerService.GetDataById(id);

			List<TblRole> listRole = await roleService.GetAllData();
			ViewBag.listRole = listRole;

			return PartialView(data);

		}

		[HttpPost]
		public async Task<IActionResult> Edit(VMCostumer dataParam)
		{
			VMResponse respon = await costumerService.Edit(dataParam);

			if (respon.Success)
			{
				return Json(new { dataRespon = respon });
			}
			return View(dataParam);
		}

		public async Task<IActionResult> Delete(int id)
		{
			VMCostumer data = await costumerService.GetDataById(id);
			return PartialView(data);
		}

		[HttpPost]
		public async Task<IActionResult> SureDelete(int id)
		{

			VMResponse respon = await costumerService.Delete(id);

			if (respon.Success)
			{
				return RedirectToAction("Index");
			}

			return RedirectToAction("Index", id);
		}
		public async Task<IActionResult> Detail(int id)
		{
			VMCostumer data = await costumerService.GetDataById(id);
			return PartialView(data);
		}
	}
}

xpos314/xpos314.web/Views/Costumer/Create.cshtml
﻿@using xpos314.viewmodels
@model VMCostumer
@{
    //Layout = null;
    ViewData["Title"] = "Create Customer";

}
<div class="card">
    <div class="card-body">
        <h2 class="display-6">@ViewData["Title"]</h2>


        <form asp-action="Create" method="post" id="form_input">
            <div class="mb-4 row a">
                <label for="NameCostumer" class="col-sm-4 col-form-label">Name Customer</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCostumer" name="NameCostumer" value="@Model.NameCostumer">

                </div>
            </div>

            <div class="mb-4 row a">
                <label for="Email" class="col-sm-4 col-form-label">Email</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Email" name="Email" value="@Model.Email">

                </div>
            </div>

            <div class="mb-4 row a">
                <label for="Password" class="col-sm-4 col-form-label">Password</label>
                <div class="col-sm-8">
                    <input type="password" class="form-control" id="Password" name="Password" value="@Model.Password">

                </div>
            </div>

            <div class="mb-4 row a">
                <label for="Address" class="col-sm-4 col-form-label">Address</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Address" name="Address" value="@Model.Address">

                </div>
            </div>

            <div class="mb-4 row a">
                <label for="Phone" class="col-sm-4 col-form-label">Phone</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Phone" name="Phone" value="@Model.Phone">

                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdRole" class="col-sm-4 col-form-label">Role Name</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdRole",
                    new SelectList(ViewBag.ListRole, "Id", "RoleName"),
                    "--Pilih Kategori--",
                    new { @class= "form-control" }
                    )
                </div>
            </div>


            <div class="mb-4 row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="Costumer" asp-action="Index">Back To List</a>
                </div>
            </div>
        </form>

    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "is-invalid text-danger",
        rules: {
            NameCostumer: {
                required: true,
                minlength: 5
            },
            Email: {
                required: true,
                email: true
            },
            Password: {
                required: true,
                minlength: 8
            },
            Address: {
                required: true,
            },
            Phone: {
                required: true,
                number: true,
                minlength: 12
            },
            IdRole: "required",
        },
        messages: {
            NameCostumer: {
                required: "Please fill name Customer!",
                minlength: "The Name must consist of at least 5 character!",
            },
            Email: {
                required: "Please fill Email",
                email: "Plese fill input email only"
            },
            Password: {
                required: "Please fill password",
                minlength: "The Name must consist of at least 8 character!"
            },
            Address: {
                required: "Please fill Address",
            },
            Phone: {
                required: "Please fill Address",
                number: "please fill number only",
                minlength: "The Phone must consist of at least 12 lenght number"
            },
            IdRole: "Plese Select Role",
        },
        submitHandler: function (form) {
            var dataForm = $(form).serialize();


            $.ajax({
                url: "/Costumer/Create",
                type: "POST",
                dataType: "json",
                data: dataForm,
                success: function (respon) {
                    var data = respon.dataRespon
                    if (data.success) {
                        $("#myModal").modal("hide")

                        toastr.success(
                            data.message,
                            '',
                            {
                                timeOut: 500,
                                fadeOut: 500,
                                onHidden: function () {
                                    window.location.reload()
                                }
                            }
                        )
                    }
                    else {
                        //Toast.fire({
                        //    icon: "Failed",
                        //    title: data.message
                        //})
                        toastr.error(data.message)
                    }
                }
            })
        }
    })


</script>

xpos314/xpos314.web/Views/Costumer/Delete.cshtml
﻿@using xpos314.datamodels
@using xpos314.viewmodels
@model VMCostumer
@{
    //Layout = null;
    ViewData["Title"] = "Delete Customer";

}

<div class="card">
    <div class="card-body">
        <div class="h6 mb-4">@ViewData["Title"]</div>
        <form asp-action="SureDelete" method="post">
            <input type="hidden" name="Id" value="@Model.Id" />

            <h4>Are you Sure for delete @Model.NameCostumer ?</h4>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-action="Index" class="btn btn-light">Back To List</a>
            </div>
        </form>

    </div>
</div>

xpos314/xpos314.web/Views/Costumer/Detail.cshtml
﻿@using xpos314.viewmodels
@model VMCostumer
@{
    //Layout = null;
    ViewData["Title"] = "Detail Customer";

}
<div class="card">
    <div class="card-body">
        <h2 class="display-6">@ViewData["Title"]</h2>


        <div class="mb-4 row a">
            <label for="NameCostumer" class="col-sm-4 col-form-label">Name Customer</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="NameCostumer" name="NameCostumer" value="@Model.NameCostumer" readonly>

            </div>
        </div>

        <div class="mb-4 row a">
            <label for="Email" class="col-sm-4 col-form-label">Email</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="Email" name="Email" value="@Model.Email" readonly>

            </div>
        </div>

        <div class="mb-4 row a">
            <label for="Password" class="col-sm-4 col-form-label">Password</label>
            <div class="col-sm-8">
                <input type="password" class="form-control" id="Password" name="Password" value="@Model.Password" readonly>

            </div>
        </div>

        <div class="mb-4 row a">
            <label for="Address" class="col-sm-4 col-form-label">Address</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="Address" name="Address" value="@Model.Address" readonly>

            </div>
        </div>

        <div class="mb-4 row a">
            <label for="Phone" class="col-sm-4 col-form-label">Phone</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="Phone" name="Phone" value="@Model.Phone" readonly>

            </div>
        </div>

        <div class="mb-4 row a">
            <label for="RoleName" class="col-sm-4 col-form-label">Role Name</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="RoleName" name="RoleName" value="@Model.RoleName" readonly>

            </div>
        </div>


        <div class="mb-4 row">
            <div class="col-sm-10">
                <a class="btn btn-light" asp-controller="Costumer" asp-action="Index">Back To List</a>
            </div>
        </div>

    </div>
</div>

xpos314/xpos314.web/Views/Costumer/Edit.cshtml
﻿@using xpos314.viewmodels
@model VMCostumer
@{
    //Layout = null;
    ViewData["Title"] = "Edit Customer";

}
<div class="card">
    <div class="card-body">
        <h2 class="display-6">@ViewData["Title"]</h2>


        <form asp-action="Edit" method="post" id="form_input">
            <input type="hidden" id="Id" name="Id" value="@Model.Id" />
            <div class="mb-4 row a">
                <label for="NameCostumer" class="col-sm-4 col-form-label">Name Customer</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCostumer" name="NameCostumer" value="@Model.NameCostumer">

                </div>
            </div>

            <div class="mb-4 row a">
                <label for="Email" class="col-sm-4 col-form-label">Email</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Email" name="Email" value="@Model.Email">

                </div>
            </div>

            <div class="mb-4 row a">
                <label for="Password" class="col-sm-4 col-form-label">Password</label>
                <div class="col-sm-8">
                    <input type="password" class="form-control" id="Password" name="Password" value="@Model.Password">

                </div>
            </div>

            <div class="mb-4 row a">
                <label for="Address" class="col-sm-4 col-form-label">Address</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Address" name="Address" value="@Model.Address">

                </div>
            </div>

            <div class="mb-4 row a">
                <label for="Phone" class="col-sm-4 col-form-label">Phone</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Phone" name="Phone" value="@Model.Phone">

                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdRole" class="col-sm-4 col-form-label">Role Name</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdRole",
                    new SelectList(ViewBag.ListRole, "Id", "RoleName"),
                    "--Pilih Role Name--",
                    new { @class= "form-control" }
                    )
                </div>
            </div>


            <div class="mb-4 row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="Costumer" asp-action="Index">Back To List</a>
                </div>
            </div>
        </form>

    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "is-invalid text-danger",
        rules: {
            NameCostumer: {
                required: true,
                minlength: 5
            },
            Email: {
                required: true,
                email: true
            },
            Password: {
                required: true,
                minlength: 8
            },
            Address: {
                required: true,
            },
            Phone: {
                required: true,
                number: true,
                minlength: 12
            },
            IdRole: "required",
        },
        messages: {
            NameCostumer: {
                required: "Please fill name Customer!",
                minlength: "The Name must consist of at least 5 character!",
            },
            Email: {
                required: "Please fill Email",
                email: "Plese fill input email only"
            },
            Password: {
                required: "Please fill password",
                minlength: "The Name must consist of at least 8 character!"
            },
            Address: {
                required: "Please fill Address",
            },
            Phone: {
                required: "Please fill Address",
                number: "please fill number only",
                minlength: "The Phone must consist of at least 12 lenght number"
            },
            IdRole: "Plese Select Role",
        },
        submitHandler: function (form) {
            var dataForm = $(form).serialize();


            $.ajax({
                url: "/Costumer/Edit",
                type: "POST",
                dataType: "json",
                data: dataForm,
                success: function (respon) {
                    var data = respon.dataRespon
                    if (data.success) {
                        $("#myModal").modal("hide")

                        toastr.success(
                            data.message,
                            '',
                            {
                                timeOut: 500,
                                fadeOut: 500,
                                onHidden: function () {
                                    window.location.reload()
                                }
                            }
                        )
                    }
                    else {
                        //Toast.fire({
                        //    icon: "Failed",
                        //    title: data.message
                        //})
                        toastr.error(data.message)
                    }
                }
            })
        }
    })


</script>

xpos314/xpos314.web/Views/Costumer/Index.cshtml
﻿@using System.Globalization
@using xpos314.datamodels
@using xpos314.viewmodels
@model PaginationList<VMCostumer>

@{
    //Layout = null;
    ViewData["Title"] = "Costumer";

}



<div class="card">
    <div class="card-header">

        <div class="row mb-3">
            <div class="col-12">
                <div class="card-title">@ViewData["Title"]</div>
                <div class="d-flex justify-content-between">
                    <button type="button" id="btn_create" class="btn btn-outline-dark">Create</button>

                    <form asp-action="Index" asp-route-pageSize="@ViewBag.CurrentPageSize">
                        <div class="input-group w-100">
                            <input type="text" name="searchString" value="@ViewBag.CurrentFilter" class="form-control" placeholder="Search">

                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default" title="search">
                                    <i class="fas fa-search"></i>
                                </button>

                                <a class="btn btn-default" asp-action="Index" title="reset">
                                    <i class="fas fa-redo"></i>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>
                            <a asp-action="Index" asp-route-sortOrder="@ViewBag.NameSort">
                                <i class="fas fa-sort"></i>
                                Name Costumer
                            </a>
                        </th>
                        <th>Email</th>
                        <th>Password</th>
                        <th>Address</th>
                        <th>Phone</th>
                        <th>Role Name</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Count != 0)
                    {
                        @foreach (VMCostumer item in Model)
                        {
                            <tr>
                                <td>@item.NameCostumer</td>
                                <td>@item.Email</td>
                                <td>@item.Password</td>
                                <td>@item.Address</td>
                                <td>@item.Phone</td>
                                <td>@item.RoleName</td>


                                <td>
                                    <button type="button" class="btn btn-outline-dark btn_edit" dataid="@item.Id">
                                        Edit
                                    </button>

                                    <button type="button" class="btn btn-outline-dark btn_detail" dataid="@item.Id">
                                        Detail
                                    </button>

                                    <button type="button" class="btn btn-outline-dark btn_delete" dataid="@item.Id">
                                        Delete
                                    </button>

                                </td>

                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="3">
                                <i>Data not found</i>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- card-body -->

        <div class="card-footer">
            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            }
            <div class="row">
                <div class="col-2">

                    <form asp-action="Index" id="form_pagesize">
                        <select name="PageSize" id="PageSize"
                                class="form-control">
                            <option value="3">3</option>
                            <option value="5">5</option>
                            <option value="10">10</option>
                        </select>
                    </form>
                </div>
                <div class="col-10">
                    Page @Model.PageIndex of @Model.TotalPages
                    <a asp-action="Index"
                       asp-route-sortOrder="@ViewBag.CurrentSort"
                       asp-route-pageNumber="@(Model.PageIndex + 1)"
                       asp-route-currentFilter="@ViewBag.CurrentFilter"
                       asp-route-pageSize="@ViewBag.CurrentPageSize"
                       class="btn btn-info float-right @nextDisabled">
                        Next
                    </a>
                    <a asp-action="Index"
                       asp-route-sortOrder="@ViewBag.CurrentSort"
                       asp-route-pageNumber="@(Model.PageIndex - 1)"
                       asp-route-currentFilter="@ViewBag.CurrentFilter"
                       asp-route-pageSize="@ViewBag.CurrentPageSize"
                       class="mr-2 btn btn-info float-right @prevDisabled">
                        Previous
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {



        $("#btn_create").click(function () {
            $("#myModal_body").empty();
            $("#myModal_body").load("/Costumer/Create")
            $("#myModal").modal("show");
        });

        $(".btn_detail").click(function () {

            var id = $(this).attr("dataid")
            $("#myModal_body").empty();
            $("#myModal_body").load("/Costumer/Detail?id=" + id)
            $("#myModal").modal("show");
        });

        $(".btn_edit").click(function () {

            var id = $(this).attr("dataid")
            $("#myModal_body").empty();
            $("#myModal_body").load("/Costumer/Edit?id=" + id)
            $("#myModal").modal("show");
        });

        $(".btn_delete").click(function () {
            var id = $(this).attr("dataid");
            $("#myModal_body").empty();
            $("#myModal_body").load("/Costumer/Delete?id=" + id)
            $("#myModal").modal("show");
        });

        $("#PageSize").val(@ViewBag.CurrentPageSize)

        $("#PageSize").change(function () {
            $("#form_pagesize").submit();
        })

    });
</script>