xpos314/xpos314.web/Controllers/CategoryTryController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class CategoryTryController : Controller
    {
        private readonly XPOS_314Context db;
        private readonly CategoryTryServices categoryTryService;
        
        public CategoryTryController(XPOS_314Context _db)
        {
            this.db = _db;
            this.categoryTryService = new CategoryTryServices(db);
        }
        public IActionResult Index()
        {
            List<VMTblCategory> dataView = categoryTryService.GetAllData();
            return View(dataView);
        }
        public IActionResult Create() 
        { 
            VMTblCategory dataView = new VMTblCategory();
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Create(VMTblCategory dataView) 
        {
            VMResponse respon = new VMResponse();

            if (ModelState.IsValid)
            {
                respon = categoryTryService.Create(dataView);

                if (respon.Success)
                {
                    return RedirectToAction("Index");
                }
            }

            respon.Entity = dataView;
            return View(respon.Entity);

        }

        public IActionResult Edit(int id)
        {
            VMTblCategory dataView = categoryTryService.GetById(id);
            return View(dataView);
        }
        [HttpPost]
        public IActionResult Edit(VMTblCategory dataView)
        {
            VMResponse respon = new VMResponse();
            if (ModelState.IsValid)
            {
                respon = categoryTryService.Edit(dataView);
                if (respon.Success)
                {
                    return RedirectToAction("Index");

                }
            }
            respon.Entity = dataView;
            return View(respon.Entity);
        }
        public IActionResult Detail(int id)
        {
            VMTblCategory dataView = categoryTryService.GetById(id);
            return View(dataView);
        }
        public IActionResult Delete(int id)
        {
            VMTblCategory dataView = categoryTryService.GetById(id);
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Delete(VMTblCategory dataView)
        {
            VMResponse respon = categoryTryService.Delete(dataView);
            if (respon.Success)
            {
                return RedirectToAction("Index");
            }
            return View(respon.Entity);

        }
    }
}

xpos314/xpos314.web/Views/CategoryTry/Create.cshtml
@using xpos314.viewmodels
@model VMTblCategory

@{
    Layout = null;
    //Layout = Model == null ? Layout : null;
    ViewData["Title"] = "Create Category";
}
<div class="card">
    <div class="card-body">

<h2 class="display-6">@ViewData["Title"]</h2>

<form asp-action="Create" method="post">
    
    <div class="form-group row">
        <label for="NameCategory" class="col-sm-4 col-form-label">Nama Category</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory">
            <span asp-validation-for="NameCategory" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label for="Description" class="col-sm-4 col-form-label">Description</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" id="Description" name="Description">
        </div>
    </div>
    
    <div class="form-group row">
        <div class="col-sm-8">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a class="btn btn-light" asp-controller="CategoryTry" asp-action="Index">Back to Index</a>
        </div>
    </div>
</form>

</div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Delete.cshtml
@using xpos314.viewmodels
@model VMTblCategory

@{
    Layout = null;
    ViewData["Title"] = "Create Detail";
}

<div class="card">
    <div class="card-body">

        <form asp-action="Delete" method="post">
            <input type="hidden" name="Id" value="@Model.Id"/>
            <h3>Are you sure for delete @Model.NameCategory ?</h3>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-action="Index" class="btn btn-light">Back to Index</a>

            </div>
        </form>

</div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Detail.cshtml
@using xpos314.viewmodels
@model VMTblCategory

@{
    Layout = null;
    ViewData["Title"] = "Create Detail";
}
<div class="card">
    <div class="card-body">

        <h2 class="display-6">@ViewData["Title"]</h2>

        
            <input type="hidden" id="Id" name="Id" value="@Model.Id" />
            @*<div class="form-group row">
            <label for="Id" class="col-sm-2 col-form-label">Id</label>
            <div class="col-sm-10">
            <input type="text" class="form-control" id="Id" name="Id">
            </div>
            </div>*@
            <div class="form-group row">
                <label for="NameCategory" class="col-sm-4 col-form-label">Nama Category</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory" readonly>
                    
                </div>
            </div>
            <div class="form-group row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description" readonly>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-8">
                   
                    <a class="btn btn-light" asp-controller="CategoryTry" asp-action="Index">Back to Index</a>
                </div>
            </div>
        

    </div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Edit.cshtml
@using xpos314.viewmodels
@model VMTblCategory

@{
    //Layout = Model == null ? Layout : null;
    Layout = null;
    ViewData["Title"] = "Edit Category";
}
<div class="card">
    <div class="card-body">

<h2 class="display-6">@ViewData["Title"]</h2>

        <form asp-action="Edit" method="post" id="form_input">
    <input type="hidden" id="Id" name="Id" value="@Model.Id" />
            @*<div class="form-group row">
        <label for="Id" class="col-sm-2 col-form-label">Id</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="Id" name="Id">
        </div>
    </div>*@
    <div class="form-group row">
        <label for="NameCategory" class="col-sm-4 col-form-label">Nama Category</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory">
            <span asp-validation-for="NameCategory" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label for="Description" class="col-sm-4 col-form-label">Description</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-8">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a class="btn btn-light" asp-controller="CategoryTry" asp-action="Index">Back to Index</a>
        </div>
    </div>
</form>

</div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Index.cshtml
@using xpos314.viewmodels;
@{
    ViewData["Title"] = "Category Try";
}


<h2 class="display-6">@ViewData["Title"]</h2>
<button type="button" class="btn btn-primary" id="btn_create">Create</button>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name Category</th>
            <th scope="col">Description</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (VMTblCategory item in Model)
        {
            <tr>
                <th scope="row">@item.Id</th>
                <td>@item.NameCategory</td>
                <td>@item.Description</td>
                <td>
                    <a class="btn btn-primary text-white btn_edit" data-id="@item.Id">Edit</a>
                    <a class="btn btn-success text-white btn_detail" data-id="@item.Id">Detail</a>
                    <a class="btn btn-danger text-white btn_delete" data-id="@item.Id">Delete</a>
                </td>
            </tr>
        }

    </tbody>
</table>

<script>
    $(document).ready(function(){
        $("#select_show").val(@ViewBag.currrentShowData)
        $("#btn_create").click(function(){
            $("#myModal_body").empty()
            $("#myModal_body").load("/CategoryTry/Create")
            $("#myModal").modal("show")
        })

        $(".btn_edit").click(function(){
            var id = $(this).data("id")
            $("#myModal_body").empty()
            $("#myModal_body").load("/CategoryTry/Edit?id=" + id)
            $("#myModal").modal("show")
        })

        $(".btn_detail").click(function(){
            var id = $(this).data("id")
            $("#myModal_body").empty()
            $("#myModal_body").load("/CategoryTry/Detail?id=" + id)
            $("#myModal").modal("show")
        })

        $(".btn_delete").click(function () {
            var id = $(this).data("id")
            $("#myModal_body").empty()
            $("#myModal_body").load("/CategoryTry/Delete?id=" + id)
            $("#myModal").modal("show")
        })

        $("#btn_search").click(function () {
            $("#sort_change").val("@ViewBag.currentSort")
            $("#form_search").submit()
        })
        $("#btn_reset").click(function () {
            $("#searchString").val("")
            $("#form_search").submit()
        })
        $("#select_show").change(function () {
            $("#sort_change").val("@ViewBag.currentSort")
            $("#form_search").submit()
        })
    })
</script>