xpos314/xpos314.web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class CategoryController : Controller
    {
        private CategoryService categoryService;
        private int IdUser = 1;

        public CategoryController(CategoryService _categoryService)
        {
            this.categoryService = _categoryService;

            //this.configuration = _configuration;
            //this.categoryService = new CategoryService(this.configuration);
        }
        public async Task <IActionResult> Index(string sortOrder, 
                                                string searchString, 
                                                string currentFilter,
                                                int? pageNumber, 
                                                int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<TblCategory> data = await categoryService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameCategory.ToLower().Contains(searchString.ToLower())
                || a.Description.ToLower().Contains(searchString.ToLower())
                ).ToList();
            }
            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameCategory).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameCategory).ToList();
                    break;
            }
            return View(PaginationList<TblCategory>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }
        
        public IActionResult Create()
        {
            TblCategory data =new TblCategory();
            return PartialView(data);
        }
        [HttpPost]
        public async Task <IActionResult> Create (TblCategory dataParam)
        {
            dataParam.CreateBy = IdUser;
            VMResponse respon = await categoryService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }
        public async Task<JsonResult> CheckNameIsExist(string nameCategory)
        {
            bool isExist = await categoryService.CheckCategoryByName(nameCategory);
            return Json(isExist);
        }
        public async Task <IActionResult> Edit (int id)
        {
            TblCategory data = await categoryService.GetDataById(id);
            return PartialView(data);
        }
        [HttpPost]
        public async Task <IActionResult> Edit(TblCategory dataParam)
        {
            dataParam.UpdateBy = IdUser;
            VMResponse respon = await categoryService.Edit(dataParam);

            if (respon.Success)
            {
				return Json(new { dataRespon = respon });
			}
            return View(dataParam);
        }
        public async Task <IActionResult> Delete(int id)
        {
            TblCategory data = await categoryService.GetDataById(id);
            return PartialView(data);
        }
        [HttpPost]
        public async Task <IActionResult> SureDelete(int id)
        {
            int createBy = IdUser;
            VMResponse respon = await categoryService.Delete(id, createBy);
            
            if (respon.Success)
            {
                return RedirectToAction("Index");
            }
            
            return RedirectToAction("Index", id);
        }
        public async Task<IActionResult> Detail(int id)
        {
            TblCategory data = await categoryService.GetDataById(id);
            return PartialView(data);
        }
        
    }
}

xpos314/xpos314.web/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
	public class RoleController : Controller
	{
		private RoleService roleService;
		private int IdUser = 1;

		public RoleController(RoleService _roleService)
		{
			this.roleService = _roleService;

		}
		public async Task<IActionResult> Index(string sortOrder,
												string searchString,
												string currentFilter,
												int? pageNumber,
												int? pageSize)
		{
			ViewBag.CurrentSort = sortOrder;
			ViewBag.CurrentPageSize = pageSize;
			ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

			if (searchString != null)
			{
				pageNumber = 1;
			}
			else
			{
				searchString = currentFilter;
			}

			ViewBag.CurrentFilter = searchString;

			List<TblRole> data = await roleService.GetAllData();

			if (!string.IsNullOrEmpty(searchString))
			{
				data = data.Where(a => a.RoleName.ToLower().Contains(searchString.ToLower())
				).ToList();
			}
			switch (sortOrder)
			{
				case "name_desc":
					data = data.OrderByDescending(a => a.RoleName).ToList();
					break;
				default:
					data = data.OrderBy(a => a.RoleName).ToList();
					break;
			}
			return View(PaginationList<TblRole>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
		}

		public IActionResult Create()
		{
			TblRole data = new TblRole();
			return PartialView(data);
		}
		[HttpPost]
		public async Task<IActionResult> Create(TblRole dataParam)
		{
			dataParam.CreateBy = IdUser;
			VMResponse respon = await roleService.Create(dataParam);

			if (respon.Success)
			{
				return Json(new { dataRespon = respon });
			}
			return View(dataParam);
		}
		public async Task<JsonResult> CheckNameIsExist(string roleName)
		{
			bool isExist = await roleService.CheckCategoryByName(roleName);
			return Json(isExist);
		}
		public async Task<IActionResult> Edit(int id)
		{
			TblRole data = await roleService.GetDataById(id);
			return PartialView(data);
		}
		[HttpPost]
		public async Task<IActionResult> Edit(TblRole dataParam)
		{
			dataParam.UpdateBy = IdUser;
			VMResponse respon = await roleService.Edit(dataParam);

			if (respon.Success)
			{
				return Json(new { dataRespon = respon });
			}
			return View(dataParam);
		}
		public async Task<IActionResult> Delete(int id)
		{
			TblRole data = await roleService.GetDataById(id);
			return PartialView(data);
		}
		[HttpPost]
		public async Task<IActionResult> SureDelete(int id)
		{
			int createBy = IdUser;
			VMResponse respon = await roleService.Delete(id, createBy);

			if (respon.Success)
			{
				return RedirectToAction("Index");
			}

			return RedirectToAction("Index", id);
		}
		public async Task<IActionResult> Detail(int id)
		{
			TblRole data = await roleService.GetDataById(id);
			return PartialView(data);
		}


	}
}

xpos314/xpos314.web/Views/Role/Create.cshtml
﻿@using xpos314.datamodels
@model TblRole
@{
	ViewData["Title"] = "Create Role";
}
<div class="card mt-4">
	<div class="card-body">
		<h4>@ViewData["Title"]</h4>
		<form asp-action="Create" method="post" id="form_input" enctype="multipart/form-data">
			<div class="form-group row mb-2">
				<label for="RoleName" class="col-sm-4 col-form-label">Role Name</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" name="RoleName" id="RoleName" required value="@Model.RoleName">
				</div>
			</div>

			<div class="form-group row">
				<div class="col-sm-10">
					<button type="submit" class="btn btn-primary">Submit</button>
					<a class="btn btn-secondary" asp-controller="Role" asp-action="Index">Back</a>
				</div>
			</div>
		</form>
	</div>
</div>


<script>
	$("#form_input").validate({
		errorClass: "is-invalid text-danger",
		rules: {
			RoleName: {
				required: true,
				minlength: 5,
			}
		},
		messages: {
			RoleName: {
				required: "Please fill name RoleName!",
				minlength: "The Name must consist of at least 5 character!",
			}
		},

		submitHandler: function (form) {
			var dataForm = $(form).serialize();


			$.ajax({
				url: "/Role/Create",
				type: "POST",
				dataType: "json",
				data: dataForm,
				success: function (respon) {
					var data = respon.dataRespon
					if (data.success) {
						$("#myModal").modal("hide")

						toastr.success(
							data.message,
							'',
							{
								timeOut: 500,
								fadeOut: 500,
								onHidden: function () {
									window.location.reload()
								}
							}
						)
					}
					else {
						toastr.error(data.message)
					}
				}
			})
		}
	})
</script>

xpos314/xpos314.web/Views/Role/Delete.cshtml
@using xpos314.datamodels
@using xpos314.viewmodels
@model TblRole

@{
    Layout = null;
    ViewData["Title"] = "Role Delete";
}

<div class="card">
    <div class="card-body">

        <form asp-action="SureDelete" method="post">
            <input type="hidden" name="Id" value="@Model.Id" />
            <h3>Are you sure for delete @Model.RoleName ?</h3>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-action="Index" class="btn btn-light">Back to Index</a>

            </div>
        </form>

    </div>
</div>

xpos314/xpos314.web/Views/Role/Detail.cshtml
﻿@using xpos314.datamodels
@model TblRole
@{
	ViewData["Title"] = "Detail Role";
}
<div class="card mt-4">
	<div class="card-body">
		<h4>@ViewData["Title"]</h4>
		<form asp-action="Edit" method="post" id="form_input" enctype="multipart/form-data">
			<div class="form-group row mb-2">
				<label for="RoleName" class="col-sm-4 col-form-label">Role Name</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" name="RoleName" id="RoleName" required value="@Model.RoleName" readonly>
					<span id="validateRole" class="text-danger"></span>
				</div>
			</div>

			<div class="form-group row">
				<div class="col-sm-10">

					<a class="btn btn-secondary" asp-controller="Role" asp-action="Index">Back</a>
				</div>
			</div>
		</form>
	</div>
</div>

xpos314/xpos314.web/Views/Role/Edit.cshtml
@using xpos314.datamodels
@model TblRole
@{
	Layout = null;
	//Layout = Model == null ? Layout : null;
	ViewData["Title"] = "Edit Role";
}
<div class="card">
	<div class="card-body">

		<h2 class="display-6">@ViewData["Title"]</h2>

		<form asp-action="Edit" method="post" id="form_input">
			<input type="hidden" name="Id" id="Id" value="@Model.Id" />

			<div class="form-group row">
				<label for="RoleName" class="col-sm-4 col-form-label">Nama Category</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" id="RoleName" name="RoleName" value="@Model.RoleName">
					<span id="validateRoleName" class="text-danger"></span>

				</div>
			</div>


			<div class="form-group row">
				<div class="col-sm-8">
					<button type="submit" class="btn btn-primary">Submit</button>
					<a class="btn btn-light" asp-controller="Category" asp-action="Index">Back to Index</a>
				</div>
			</div>
		</form>

	</div>
</div>


<script>
	$("#form_input").validate({
		errorClass: "is-invalid text-danger",
		rules: {
			RoleName: {
				required: true,
				minlength: 5,
			}
		},
		messages: {
			RoleName: {
				required: "Please fill name RoleName!",
				minlength: "The Name must consist of at least 5 character!",
			}
		},

		submitHandler: function (form) {
			var dataForm = $(form).serialize();


			$.ajax({
				url: "/Role/Edit",
				type: "POST",
				dataType: "json",
				data: dataForm,
				success: function (respon) {
					var data = respon.dataRespon
					if (data.success) {
						$("#myModal").modal("hide")

						toastr.success(
							data.message,
							'',
							{
								timeOut: 500,
								fadeOut: 500,
								onHidden: function () {
									window.location.reload()
								}
							}
						)
					}
					else {
						toastr.error(data.message)
					}
				}
			})
		}
	})
</script>

xpos314/xpos314.web/Views/Role/Index.cshtml
﻿@using xpos314.datamodels
@using xpos314.viewmodels
@model PaginationList<TblRole>

@{
    //Layout = null;
    ViewData["Title"] = "Role Page";

}

<div class="card">
    <div class="card-header">

        <div class="row mb-3">
            <div class="col-12">
                <div class="card-title">@ViewData["Title"]</div>
                <div class="d-flex justify-content-between">
                    <button type="button" id="btn_create" class="btn btn-outline-dark">Create</button>

                    <form asp-action="Index" asp-route-pageSize="@ViewBag.CurrentPageSize">
                        <div class="input-group w-100">
                            <input type="text" name="searchString" value="@ViewBag.CurrentFilter" class="form-control" placeholder="Search">

                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default" title="search">
                                    <i class="fas fa-search"></i>
                                </button>

                                <a class="btn btn-default" asp-action="Index" title="reset">
                                    <i class="fas fa-redo"></i>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>

                        <th>
                            <a asp-action="Index" asp-route-sortOrder="@ViewBag.NameSort">
                                <i class="fas fa-sort"></i>
                                Role Name
                            </a>
                        </th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Count != 0)
                    {
                        @foreach (TblRole item in Model)
                        {
                            <tr>

                                <td>@item.RoleName</td>



                                <td>
                                    <button type="button" class="btn btn-outline-dark btn_edit" dataid="@item.Id">
                                        Edit
                                    </button>

                                    <button type="button" class="btn btn-outline-dark btn_detail" dataid="@item.Id">
                                        Detail
                                    </button>

                                    <button type="button" class="btn btn-outline-dark btn_delete" dataid="@item.Id">
                                        Delete
                                    </button>

                                </td>

                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="3">
                                <i>Data not found</i>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- card-body -->

        <div class="card-footer">
            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            }
            <div class="row">
                <div class="col-2">

                    <form asp-action="Index" id="form_pagesize">
                        <select name="PageSize" id="PageSize"
                                class="form-control">
                            <option value="3">3</option>
                            <option value="5">5</option>
                            <option value="10">10</option>
                        </select>
                    </form>
                </div>
                <div class="col-10">
                    Page @Model.PageIndex of @Model.TotalPages
                    <a asp-action="Index"
                       asp-route-sortOrder="@ViewBag.CurrentSort"
                       asp-route-pageNumber="@(Model.PageIndex + 1)"
                       asp-route-currentFilter="@ViewBag.CurrentFilter"
                       asp-route-pageSize="@ViewBag.CurrentPageSize"
                       class="btn btn-info float-right @nextDisabled">
                        Next
                    </a>
                    <a asp-action="Index"
                       asp-route-sortOrder="@ViewBag.CurrentSort"
                       asp-route-pageNumber="@(Model.PageIndex - 1)"
                       asp-route-currentFilter="@ViewBag.CurrentFilter"
                       asp-route-pageSize="@ViewBag.CurrentPageSize"
                       class="btn btn-info float-right @prevDisabled">
                        Previous
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        $("#btn_create").click(function () {
            $("#myModal_body").empty();
            $("#myModal_body").load("/Role/Create")
            $("#myModal").modal("show");
        });

        $(".btn_detail").click(function () {

            var id = $(this).attr("dataid")
            $("#myModal_body").empty();
            $("#myModal_body").load("/Role/Detail?id=" + id)
            $("#myModal").modal("show");
        });

        $(".btn_edit").click(function () {

            var id = $(this).attr("dataid")
            $("#myModal_body").empty();
            $("#myModal_body").load("/Role/Edit?id=" + id)
            $("#myModal").modal("show");
        });

        $(".btn_delete").click(function () {
            var id = $(this).attr("dataid");
            $("#myModal_body").empty();
            $("#myModal_body").load("/Role/Delete?id=" + id)
            $("#myModal").modal("show");
        });

        $("#PageSize").val(@ViewBag.CurrentPageSize)

        $("#PageSize").change(function () {
            $("#form_pagesize").submit();
        })

    });
</script>